version: "3.3"
services:
  db:
    container_name: "mongodb"
    image: mongo
    restart: always
    ports:
    - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
  redis:
    image: redis:7.0-rc-alpine3.15
    restart: always
    ports:
      - '6379:6379'